# Generated by Django 6.0.4 on 2026-05-01 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('edad_minima', models.IntegerField(verbose_name='Edad mínima')),
                ('edad_maxima', models.IntegerField(verbose_name='Edad máxima')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='torneos.torneo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
