# Generated by Django 6.0.4 on 2026-05-01 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0005_jugador_dorsal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_JUEGO', 'En juego'), ('FINALIZADO', 'Finalizado'), ('APLAZADO', 'Aplazado'), ('SUSPENDIDO', 'Suspendido'), ('WO', 'W.O.'), ('COMITE', 'Decidido por comité')], default='PROGRAMADO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.categoria')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='torneos.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='torneos.equipo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
    ]
