# Generated by Django 6.0.4 on 2026-05-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0006_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='cancha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cancha'),
        ),
        migrations.AddField(
            model_name='partido',
            name='numero_fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha del fixture'),
        ),
    ]
