# Generated by Django 6.0.4 on 2026-05-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0007_partido_cancha_partido_numero_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='grupo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Grupo'),
        ),
    ]
