# Generated by Django 6.0.4 on 2026-05-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0008_partido_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fase',
            field=models.CharField(choices=[('GRUPOS', 'Fase de grupos'), ('CUARTOS', 'Cuartos de final'), ('SEMIFINAL', 'Semifinal'), ('FINAL', 'Final')], default='GRUPOS', max_length=20, verbose_name='Fase'),
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles_registrados', to='torneos.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='torneos.partido')),
            ],
            options={
                'verbose_name': 'Gol',
                'verbose_name_plural': 'Goles',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AMARILLA', 'Amarilla'), ('ROJA', 'Roja')], max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_recibidas', to='torneos.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='torneos.partido')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
    ]
