# Generated by Django 6.0.4 on 2026-05-02 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0009_partido_fase_gol_tarjeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['categoria__nombre', 'grupo', 'numero_fecha', 'fecha', 'hora'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='torneos.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='torneos.equipo'),
        ),
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GOL', 'Gol'), ('A', 'Amarilla'), ('R', 'Roja')], max_length=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='torneos.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='torneos.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='torneos.partido')),
            ],
            options={
                'verbose_name': 'Evento del partido',
                'verbose_name_plural': 'Eventos del partido',
            },
        ),
    ]
