# Generated by Django 6.0.4 on 2026-05-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0010_alter_partido_options_alter_partido_equipo_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='ajuste_puntos_local',
            field=models.IntegerField(default=0, verbose_name='Ajuste puntos local'),
        ),
        migrations.AddField(
            model_name='partido',
            name='ajuste_puntos_visitante',
            field=models.IntegerField(default=0, verbose_name='Ajuste puntos visitante'),
        ),
        migrations.AddField(
            model_name='partido',
            name='observacion_comite',
            field=models.TextField(blank=True, null=True, verbose_name='Observación del comité'),
        ),
    ]
