# Generated by Django 6.0.4 on 2026-05-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0011_partido_ajuste_puntos_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_JUEGO', 'En juego'), ('FINALIZADO', 'Finalizado'), ('APLAZADO', 'Aplazado'), ('SUSPENDIDO', 'Suspendido'), ('WO', 'W.O.'), ('DECIDIDO_COMITE', 'Decidido por comité'), ('DEMANDA', 'Demanda / reclamación')], default='PROGRAMADO', max_length=30),
        ),
    ]
