# Generated by Django 6.0.4 on 2026-05-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0012_alter_partido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_JUEGO', 'En juego'), ('FINALIZADO', 'Finalizado'), ('APLAZADO', 'Aplazado'), ('SUSPENDIDO', 'Suspendido'), ('WO', 'W.O.'), ('DEMANDA_DECIDIDO_COMITE', 'Decidido por comité')], default='PROGRAMADO', max_length=30),
        ),
    ]
