# Generated by Django 6.0.4 on 2026-05-05 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0013_alter_partido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='goles_local_penales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_visitante_penales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='siguiente_partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_origen', to='torneos.partido', verbose_name='Partido siguiente'),
        ),
        migrations.AddField(
            model_name='partido',
            name='slot_siguiente',
            field=models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('VISITANTE', 'Visitante')], max_length=20, null=True, verbose_name='Entra como'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_JUEGO', 'En juego'), ('FINALIZADO', 'Finalizado'), ('APLAZADO', 'Aplazado'), ('SUSPENDIDO', 'Suspendido'), ('WO', 'W.O.'), ('DECIDIDO_COMITE', 'Decidido por comité')], default='PROGRAMADO', max_length=30),
        ),
    ]
