# Generated by Django 6.0.4 on 2026-05-08 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0014_partido_goles_local_penales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='fase',
            field=models.CharField(choices=[('GRUPOS', 'Fase de grupos'), ('CUARTOS', 'Cuartos de final'), ('SEMIFINAL', 'Semifinal'), ('FINAL', 'Final'), ('TERCER_PUESTO', 'Tercer puesto')], default='GRUPOS', max_length=20, verbose_name='Fase'),
        ),
        migrations.CreateModel(
            name='SustitucionPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=150, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustituciones_partido', to='torneos.equipo')),
                ('jugador_entra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustituciones_entra', to='torneos.jugador')),
                ('jugador_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustituciones_sale', to='torneos.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustituciones', to='torneos.partido')),
            ],
            options={
                'verbose_name': 'Sustitución del partido',
                'verbose_name_plural': 'Sustituciones del partido',
                'ordering': ['equipo__nombre', 'minuto', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AlineacionPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('TITULAR', 'Titular'), ('SUPLENTE', 'Suplente')], default='TITULAR', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones_partido', to='torneos.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones_partido', to='torneos.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='torneos.partido')),
            ],
            options={
                'verbose_name': 'Alineación del partido',
                'verbose_name_plural': 'Alineaciones del partido',
                'ordering': ['equipo__nombre', 'rol', 'jugador__nombres'],
                'unique_together': {('partido', 'jugador')},
            },
        ),
    ]
