# Generated by Django 6.0.4 on 2026-05-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0015_alter_partido_fase_sustitucionpartido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='asistente_tecnico',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Asistente técnico'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='director_tecnico',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Director técnico'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='telefono_at',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Celular AT'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='telefono_dt',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Celular DT'),
        ),
    ]
