# Generated by Django 6.0.4 on 2026-05-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0016_equipo_asistente_tecnico_equipo_director_tecnico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Celular delegado'),
        ),
    ]
