# Generated by Django 6.0.4 on 2026-05-17 06:04

import torneos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0018_equipo_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to=torneos.models.ruta_escudo_equipo, verbose_name='Escudo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=torneos.models.ruta_foto_jugador, verbose_name='Foto'),
        ),
    ]
