# Generated by Django 6.0.4 on 2026-05-17 17:54

import torneos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0019_alter_equipo_escudo_alter_jugador_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REGLAMENTO', 'Reglamento'), ('RESOLUCION', 'Resolución'), ('DEMANDA', 'Demanda')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to=torneos.models.ruta_documento, verbose_name='Archivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['tipo', '-creado_en', 'titulo'],
            },
        ),
    ]
