# Generated by Django 6.0.4 on 2026-05-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0020_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.URLField(max_length=600, verbose_name='Archivo'),
        ),
    ]
