# Generated by Django 6.0.4 on 2026-05-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0021_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('REGLAMENTO', 'Reglamento'), ('RESOLUCION', 'Resolución'), ('DEMANDA', 'Demanda'), ('COMUNICADO', 'Comunicado')], max_length=20, verbose_name='Tipo'),
        ),
    ]
