# Generated by Django 6.0.4 on 2026-05-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0023_torneo_y_documentos_por_torneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='inicio_en_vivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
