# Generated by Django 6.0.4 on 2026-05-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0024_partido_inicio_en_vivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='inicio_en_vivo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio real en vivo'),
        ),
    ]
