# Generated by Django 6.0.4 on 2026-05-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0025_alter_partido_inicio_en_vivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='cronometro_pausado',
            field=models.BooleanField(default=False, verbose_name='Cronómetro pausado'),
        ),
        migrations.AddField(
            model_name='partido',
            name='segundos_acumulados',
            field=models.PositiveIntegerField(default=0, verbose_name='Segundos acumulados'),
        ),
    ]
