# Generated by Django 6.0.4 on 2026-05-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0026_partido_cronometro_pausado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='periodo_en_vivo',
            field=models.CharField(blank=True, choices=[('PT', 'Primer tiempo'), ('ET', 'Entretiempo'), ('ST', 'Segundo tiempo'), ('FIN', 'Finalizado')], default='PT', max_length=5),
        ),
    ]
