# Generated by Django 6.0.4 on 2026-05-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0027_partido_periodo_en_vivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='cronometro_pausado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partido',
            name='inicio_en_vivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='segundos_acumulados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
