# Generated by Django 6.0.4 on 2026-05-21 21:45

import torneos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0029_torneo_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='imagen_central',
            field=models.ImageField(blank=True, null=True, upload_to=torneos.models.ruta_imagen_central_torneo, verbose_name='Imagen central del encabezado'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='lema',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Lema'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='logo_derecho',
            field=models.ImageField(blank=True, null=True, upload_to=torneos.models.ruta_logo_derecho_torneo, verbose_name='Logo derecho del encabezado'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='logo_izquierdo',
            field=models.ImageField(blank=True, null=True, upload_to=torneos.models.ruta_logo_izquierdo_torneo, verbose_name='Logo izquierdo del encabezado'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='logo_portada',
            field=models.ImageField(blank=True, null=True, upload_to=torneos.models.ruta_logo_portada_torneo, verbose_name='Logo de portada'),
        ),
    ]
