# Generated by Django 6.0.4 on 2026-05-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0032_organizador_independiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alineacionpartido',
            name='rol',
            field=models.CharField(choices=[('TITULAR', 'Titular'), ('SUPLENTE', 'Suplente'), ('NO_DISPONIBLE', 'No disponible')], default='TITULAR', max_length=20),
        ),
    ]
