# Generated by Django 6.0.4 on 2026-05-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0033_alter_alineacionpartido_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='alineacionpartido',
            name='posicion_cancha',
            field=models.CharField(blank=True, choices=[('POR', 'Arquero'), ('LI', 'Lateral izquierdo'), ('DFC1', 'Central izquierdo'), ('DFC2', 'Central derecho'), ('LD', 'Lateral derecho'), ('MC1', 'Medio izquierdo'), ('MC2', 'Medio centro'), ('MC3', 'Medio derecho'), ('EI', 'Extremo izquierdo'), ('DC', 'Delantero centro'), ('ED', 'Extremo derecho')], default='', max_length=10, verbose_name='Posición en cancha'),
        ),
    ]
