# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0034_alineacionpartido_posicion_cancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gol',
            name='es_autogol',
            field=models.BooleanField(default=False, verbose_name='Autogol'),
        ),
        migrations.AddField(
            model_name='gol',
            name='es_penal',
            field=models.BooleanField(default=False, verbose_name='Gol de penal'),
        ),
    ]
