# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneos", "0041_partido_planilleros"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="acceso_delegado_hasta",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Acceso delegado hasta"),
        ),
    ]
