# Generated by Codex on 2026-06-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneos", "0042_equipo_acceso_delegado_hasta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partido",
            name="estadisticas_validadas",
            field=models.BooleanField(default=True, verbose_name="Estadísticas validadas"),
        ),
        migrations.AddField(
            model_name="partido",
            name="estadisticas_validadas_en",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Estadísticas validadas en"),
        ),
        migrations.AddField(
            model_name="partido",
            name="estadisticas_validadas_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partidos_estadisticas_validadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Estadísticas validadas por",
            ),
        ),
    ]
