# Generated by Django 6.0.4 on 2026-06-01 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0043_partido_validacion_estadisticas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=40)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objeto_repr', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad', to='torneos.torneo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AdminTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_editar', models.BooleanField(default=True)),
                ('puede_validar', models.BooleanField(default=True)),
                ('puede_programar', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins_asignados', to='torneos.torneo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos_administrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin de torneo',
                'verbose_name_plural': 'Admins de torneo',
                'ordering': ['torneo__nombre', 'usuario__username'],
                'unique_together': {('usuario', 'torneo')},
            },
        ),
    ]
