# Generated by Django 6.0.4 on 2026-06-01 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0044_registroactividad_admintorneo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOrganizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_editar', models.BooleanField(default=True)),
                ('puede_validar', models.BooleanField(default=True)),
                ('puede_programar', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins_asignados', to='torneos.organizador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizadores_administrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin de organizador',
                'verbose_name_plural': 'Admins de organizador',
                'ordering': ['organizador__nombre', 'usuario__username'],
                'unique_together': {('usuario', 'organizador')},
            },
        ),
    ]
