# Generated by Django 6.0.4 on 2026-06-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0045_adminorganizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='estado_programacion',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SUGERIDA', 'Sugerida'), ('OFICIAL', 'Oficial')], default='MANUAL', max_length=20, verbose_name='Estado de programacion'),
        ),
    ]
