# Generated by Django 6.0.4 on 2026-06-03 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0046_partido_estado_programacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTADISTICAS', 'Estadisticas de partido'), ('EQUIPO', 'Edicion de equipo'), ('JUGADOR', 'Edicion de jugador')], max_length=30)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_validacion_creadas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_validacion', to='torneos.equipo')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_validacion', to='torneos.jugador')),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_validacion', to='torneos.partido')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_validacion_resueltas', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_validacion', to='torneos.torneo')),
            ],
            options={
                'verbose_name': 'Solicitud de validacion',
                'verbose_name_plural': 'Solicitudes de validacion',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado', 'tipo'], name='torneos_sol_estado_5a998e_idx'), models.Index(fields=['torneo', 'estado'], name='torneos_sol_torneo__dbe00e_idx')],
            },
        ),
    ]
