# Generated by Django 6.0.4 on 2026-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0047_solicitudvalidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminorganizador',
            name='puede_descargar_planillas',
            field=models.BooleanField(default=False, verbose_name='Puede descargar planillas'),
        ),
        migrations.AddField(
            model_name='admintorneo',
            name='puede_descargar_planillas',
            field=models.BooleanField(default=False, verbose_name='Puede descargar planillas'),
        ),
    ]
