# Generated by Django 6.0.4 on 2026-07-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0049_reglaedadcategoria_maximo_titulares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudvalidacion',
            name='tipo',
            field=models.CharField(choices=[('ESTADISTICAS', 'Estadisticas de partido'), ('EQUIPO', 'Edicion de equipo'), ('JUGADOR', 'Edicion de jugador'), ('ALINEACION', 'Validacion de alineacion')], max_length=30),
        ),
    ]
