# Generated by Django 6.0.4 on 2026-07-10 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0050_alter_solicitudvalidacion_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alineacionpartido',
            name='documento_validado',
            field=models.BooleanField(default=False, verbose_name='Documento validado'),
        ),
        migrations.AddField(
            model_name='alineacionpartido',
            name='documento_validado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Documento validado en'),
        ),
        migrations.AddField(
            model_name='alineacionpartido',
            name='documento_validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_alineacion_validados', to=settings.AUTH_USER_MODEL),
        ),
    ]
