# Generated by Django 6.0.4 on 2026-07-12 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0051_alineacionpartido_documento_validado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='cargado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_planilla_cargados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_planilla', to='torneos.categoria'),
        ),
        migrations.AddField(
            model_name='documento',
            name='equipo_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_planilla_local', to='torneos.equipo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='equipo_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_planilla_visitante', to='torneos.equipo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_partido',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha jugada'),
        ),
        migrations.AddField(
            model_name='documento',
            name='hora_partido',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora jugada'),
        ),
        migrations.AddField(
            model_name='documento',
            name='numero_fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha del fixture'),
        ),
        migrations.AddField(
            model_name='documento',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_planilla', to='torneos.partido'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('REGLAMENTO', 'Reglamento'), ('RESOLUCION', 'Resolución'), ('DEMANDA', 'Demanda'), ('COMUNICADO', 'Comunicado'), ('PLANILLA_JUEGO', 'Planilla de juego')], max_length=20, verbose_name='Tipo'),
        ),
    ]
