# Generated by Django 6.0.4 on 2026-07-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0052_documento_cargado_por_documento_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='delegado_puede_cargar_fotos_jugadores',
            field=models.BooleanField(default=True, verbose_name='Delegado puede cargar fotos de jugadores'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='delegado_puede_editar_equipo',
            field=models.BooleanField(default=True, verbose_name='Delegado puede editar equipo y jugadores'),
        ),
    ]
