# Generated by Django 6.0.4 on 2026-07-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0061_equipo_administrador_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='canchas_habilitadas',
            field=models.TextField(blank=True, help_text='Escribe una cancha por línea.', verbose_name='Canchas habilitadas'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('ARCHIVADO', 'Archivado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
    ]
