# Generated by Django 6.0.4 on 2026-08-13 06:36

import contabilidad.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torneos', '0065_equipo_telefono_administrador_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_amarilla', models.DecimalField(decimal_places=2, default=Decimal('5000'), max_digits=12)),
                ('valor_roja', models.DecimalField(decimal_places=2, default=Decimal('8000'), max_digits=12)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('torneo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contabilidad_configuracion', to='torneos.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inscripcion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contabilidad_cuentas', to='torneos.categoria')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contabilidad_cuenta', to='torneos.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contabilidad_cuentas', to='torneos.torneo')),
            ],
            options={
                'ordering': ['categoria__nombre', 'equipo__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=180)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('forma_pago', models.CharField(default='Efectivo', max_length=40)),
                ('soporte', models.ImageField(blank=True, null=True, upload_to=contabilidad.models.ruta_soporte)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='torneos.categoria')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contabilidad_egresos_registrados', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contabilidad_egresos', to='torneos.torneo')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INSCRIPCION', 'Inscripción'), ('TARJETAS', 'Pago de tarjetas'), ('OTRO', 'Otro')], max_length=20)),
                ('concepto', models.CharField(max_length=180)),
                ('detalle', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('forma_pago', models.CharField(default='Efectivo', max_length=40)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='torneos.categoria')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='torneos.equipo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contabilidad_ingresos_registrados', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contabilidad_ingresos', to='torneos.torneo')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AbonoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contabilidad_abonos_registrados', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='contabilidad.cuentaequipo')),
                ('ingreso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abono_inscripcion', to='contabilidad.ingreso')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PagoTarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_amarillas', models.PositiveIntegerField(default=0)),
                ('cantidad_rojas', models.PositiveIntegerField(default=0)),
                ('valor_unitario_amarilla', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_unitario_roja', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_tarjetas', to='contabilidad.cuentaequipo')),
                ('ingreso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_tarjetas', to='contabilidad.ingreso')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contabilidad_pagos_tarjetas_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CobroTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tarjeta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cobro_contable', to='torneos.tarjeta')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_tarjetas', to='contabilidad.cuentaequipo')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='contabilidad.pagotarjetas')),
            ],
        ),
    ]
