# Generated by Django 6.0.4 on 2026-08-13 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('torneos', '0065_equipo_telefono_administrador_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contabilidad_cuentas', to='torneos.equipo'),
        ),
        migrations.AddConstraint(
            model_name='cuentaequipo',
            constraint=models.UniqueConstraint(fields=('torneo', 'equipo'), name='cuenta_contable_unica_torneo_equipo'),
        ),
    ]
