# Generated by Django 6.0.4 on 2026-08-14 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_alter_cuentaequipo_equipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='egreso',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egreso',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contabilidad_egresos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egreso',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contabilidad_ingresos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
