# Generated by Django 6.0.4 on 2026-08-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_egreso_anulado_egreso_anulado_en_egreso_anulado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='dia_limite_mensualidad',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='mensualidades_habilitadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='mes_fin_mensualidades',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='mes_inicio_mensualidades',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='valor_mensualidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='periodo_mensualidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='tipo',
            field=models.CharField(choices=[('INSCRIPCION', 'Inscripción'), ('TARJETAS', 'Pago de tarjetas'), ('MENSUALIDAD', 'Pago de mensualidad'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
